[tools]
bat = "latest"
lsd = "latest"
ripgrep = "latest"
lazygit = "latest"
fzf = "latest"
fd = "latest"
neovim = "0.10.4"
node = "latest"
usage = "latest" 
chezmoi = "latest"

# "ubi:fluxcd/flux2" = { version = "latest", exe = "flux" }
